sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Jkluio123456@@
  alioss: # TODO 修改成amazon s3的密钥
    endpoint: oss-us-east-1.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: zh-personal-project
  redis:
    host: localhost
    port: 6379
    password: Jkluio123456@@
    database: 10
  wechat:
    appid:
    secret:
